/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransfersRouteImport } from './routes/transfers'
import { Route as MarketRouteImport } from './routes/market'
import { Route as HoldingsRouteImport } from './routes/holdings'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TransfersIdRouteImport } from './routes/transfers.$id'
import { Route as HoldingsIdRouteImport } from './routes/holdings.$id'

const TransfersRoute = TransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const HoldingsRoute = HoldingsRouteImport.update({
  id: '/holdings',
  path: '/holdings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransfersIdRoute = TransfersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TransfersRoute,
} as any)
const HoldingsIdRoute = HoldingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => HoldingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/holdings': typeof HoldingsRouteWithChildren
  '/market': typeof MarketRoute
  '/transfers': typeof TransfersRouteWithChildren
  '/holdings/$id': typeof HoldingsIdRoute
  '/transfers/$id': typeof TransfersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/holdings': typeof HoldingsRouteWithChildren
  '/market': typeof MarketRoute
  '/transfers': typeof TransfersRouteWithChildren
  '/holdings/$id': typeof HoldingsIdRoute
  '/transfers/$id': typeof TransfersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/holdings': typeof HoldingsRouteWithChildren
  '/market': typeof MarketRoute
  '/transfers': typeof TransfersRouteWithChildren
  '/holdings/$id': typeof HoldingsIdRoute
  '/transfers/$id': typeof TransfersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/holdings'
    | '/market'
    | '/transfers'
    | '/holdings/$id'
    | '/transfers/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/holdings'
    | '/market'
    | '/transfers'
    | '/holdings/$id'
    | '/transfers/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/holdings'
    | '/market'
    | '/transfers'
    | '/holdings/$id'
    | '/transfers/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  HoldingsRoute: typeof HoldingsRouteWithChildren
  MarketRoute: typeof MarketRoute
  TransfersRoute: typeof TransfersRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transfers': {
      id: '/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof TransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/holdings': {
      id: '/holdings'
      path: '/holdings'
      fullPath: '/holdings'
      preLoaderRoute: typeof HoldingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfers/$id': {
      id: '/transfers/$id'
      path: '/$id'
      fullPath: '/transfers/$id'
      preLoaderRoute: typeof TransfersIdRouteImport
      parentRoute: typeof TransfersRoute
    }
    '/holdings/$id': {
      id: '/holdings/$id'
      path: '/$id'
      fullPath: '/holdings/$id'
      preLoaderRoute: typeof HoldingsIdRouteImport
      parentRoute: typeof HoldingsRoute
    }
  }
}

interface HoldingsRouteChildren {
  HoldingsIdRoute: typeof HoldingsIdRoute
}

const HoldingsRouteChildren: HoldingsRouteChildren = {
  HoldingsIdRoute: HoldingsIdRoute,
}

const HoldingsRouteWithChildren = HoldingsRoute._addFileChildren(
  HoldingsRouteChildren,
)

interface TransfersRouteChildren {
  TransfersIdRoute: typeof TransfersIdRoute
}

const TransfersRouteChildren: TransfersRouteChildren = {
  TransfersIdRoute: TransfersIdRoute,
}

const TransfersRouteWithChildren = TransfersRoute._addFileChildren(
  TransfersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  HoldingsRoute: HoldingsRouteWithChildren,
  MarketRoute: MarketRoute,
  TransfersRoute: TransfersRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
